steps:
 # This step builds the container image. This is how to make comments in yaml file
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-leo:latest" # This refers to a dock registry, we will use GCR
      - "."
      # timeout: 1800s, this is not necessay but a timeout of 1800s is 30 mins
      # In google image we are using a docker image to build a docker image
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: 
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-leo:latest"
    #This step will deploy the dev application in Kubernetes
    name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy
    args:
    - run
    - --filename=manifest.yaml
    - --image=gcr.io/project_funky_flex/stedi-leo:latest
    - --location=us-east4-b
    - --output=/tmp/outputdev
    - --cluster=cluster-1



  - name: "gcr.io/cloud-builders/docker"
    id: Run # This step will run a test file (aka step 3)
    args:
      - "run"
      - "gcr.io/project_funky_flex/stedi-leo:latest"



