#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leo-stedi
  template:
    metadata:
      labels:
        app: leo-stedi
    spec:
      containers:
        - name: leo-stedi
          image: gcr.io/project-funky-flex/stedi-leo:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
